### ISSUE TITLE
node app // Error: Cannot find module 'cookie-parser'

### ISSUE THREAD

**Issue by Buzzeron** [raywo/MMM-NowPlayingOnSpotify#64]
Been the whole day trying to fix this error.

I can't turn on the app!! After typing "node app" on authorization It throws this error: 

@raspberrypi:~/MagicMirror/modules/MMM-NowPlayingOnSpotify/authorization $ node app
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cookie-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify/authorization/app.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by AnthonyVPham** [comment]
Be sure you're in the MMM-NowPlayingOnSpotify folder when you npm install. Then try going into the authorization folder and "node app" again.

**Comment by Buzzeron** [comment]
I re images raspian and worked perfectly 😅😇
