### ISSUE TITLE
Failed Install - "unexpected end of JSON input while parsing"

### ISSUE THREAD

**Issue by Diminished7th** [raywo/MMM-NowPlayingOnSpotify#74]
Hi all, I'm hoping someone can help me here.  I followed all of the instructions for install, but when I do a npm install, I get the following error:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-NowPlayingOnSpotify $ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...l-checks","npm-packag'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-16T19_23_34_892Z-debug.log
```

And this is from the log in case it helps troubleshoot:

```
267 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...l-checks","npm-packag'
267 verbose stack     at JSON.parse (<anonymous>)
267 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
267 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
267 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
268 verbose cwd /home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify
269 verbose Linux 4.19.118-v7l+
270 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install"
271 verbose node v10.21.0
272 verbose npm  v6.14.6
273 error Unexpected end of JSON input while parsing near '...l-checks","npm-packag'
274 verbose exit [ 1, true ]
```

**Comment by Diminished7th** [comment]
Self-resolved lol.  For the record, if anyone else has this issue, I was able to resolve with a cache clean:

`npm cache clean --force`
