### ISSUE TITLE
MMM-NowPlayingOnSpotify stop working after v2.13 update

### ISSUE THREAD

**Issue by Ra7t0r** [raywo/MMM-NowPlayingOnSpotify#79]
Hello.
I get the following error since I updated to MM v2.13

0|mm     | [2020-10-03 19:55:18.881] [ERROR]  
0|mm     | Can’t retrieve current song. Reason: 
0|mm     | [2020-10-03 19:55:18.882] [ERROR]  
0|mm     | RequestError: Error: Client network socket disconnected before secure TLS connection was established
0|mm     |     at new RequestError (/home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_modules/request-promise-core/lib/errors.js:14:15)
0|mm     |     at Request.plumbing.callback (/home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_modules/request-promise-core/lib/plumbing.js:87:29)
0|mm     |     at Request.RP$callback [as _callback] (/home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_modules/request-promise-core/lib/plumbing.js:46:31)
0|mm     |     at self.callback (/home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_modules/request/request.js:185:22)
0|mm     |     at Request.emit (events.js:200:13)
0|mm     |     at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_modules/request/request.js:877:8)
0|mm     |     at ClientRequest.emit (events.js:200:13)
0|mm     |     at TLSSocket.socketErrorListener (_http_client.js:402:9)
0|mm     |     at TLSSocket.emit (events.js:200:13)
0|mm     |     at emitErrorNT (internal/streams/destroy.js:91:8) {
0|mm     |   name: 'RequestError',
0|mm     |   message: 'Error: Client network socket disconnected ' +
0|mm     |     'before secure TLS connection was ' +
0|mm     |     'established',
0|mm     |   cause: Error: Client network socket disconnected before secure TLS connection was established
0|mm     |       at connResetException (internal/errors.js:559:14)
0|mm     |       at TLSSocket.onConnectEnd (_tls_wrap.js:1355:19)
0|mm     |       at Object.onceWrapper (events.js:288:20)
0|mm     |       at TLSSocket.emit (events.js:205:15)
0|mm     |       at endReadableNT (_stream_readable.js:1154:12)
0|mm     |       at processTicksAndRejections (internal/process/task_queues.js:84:9) {
0|mm     |     code: 'ECONNRESET',
0|mm     |     path: null,
0|mm     |     host: 'api.spotify.com',
0|mm     |     port: 443,
0|mm     |     localAddress: undefined
0|mm     |   },
0|mm     |   error: Error: Client network socket disconnected before secure TLS connection was established
0|mm     |       at connResetException (internal/errors.js:559:14)
0|mm     |       at TLSSocket.onConnectEnd (_tls_wrap.js:1355:19)
0|mm     |       at Object.onceWrapper (events.js:288:20)
0|mm     |       at TLSSocket.emit (events.js:205:15)
0|mm     |       at endReadableNT (_stream_readable.js:1154:12)
0|mm     |       at processTicksAndRejections (internal/process/task_queues.js:84:9) {
0|mm     |     code: 'ECONNRESET',
0|mm     |     path: null,
0|mm     |     host: 'api.spotify.com',
0|mm     |     port: 443,
0|mm     |     localAddress: undefined
0|mm     |   },
0|mm     |   options: {
0|mm     |     url: 'https://api.spotify.com/v1/me/player',
0|mm     |     headers: {
0|mm     |       Authorization: 'Bearer ' +
0|mm     |         'BQBRDGEfWRoLJxBqiqioyoWh4GE5glEZQtZKAmgwYj8PiRhKDh9l796Ehlo7URvaB-_22gnk2Ybr7OxENlnlZS9S247mYnDa7-yzRnw0B6jug8-arHzcWMUr8xViOkVJMsKGink3bHhdiNmezkfFeA'
0|mm     |     },
0|mm     |     json: true,
0|mm     |     method: 'GET',
0|mm     |     callback: [Function: RP$callback],
0|mm     |     transform: undefined,
0|mm     |     simple: true,
0|mm     |     resolveWithFullResponse: false,
0|mm     |     transform2xxOnly: false
0|mm     |   },
0|mm     |   response: undefined
0|mm     | }

Any suggestions?

**Comment by Ra7t0r** [comment]
The problem seems to be cached api.spotify.com IP address. flush dns servers records and works again.
